"""fresh schema 20 tables postgis

Revision ID: 05a3e57096d8
Revises: 
Create Date: 2026-09-22 22:14:01.365878

"""


from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '05a3e57096d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('parent_department_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(code) > 0', name=op.f('ck_departments_ck_departments_code')),
    sa.CheckConstraint('char_length(name) > 0', name=op.f('ck_departments_ck_departments_name')),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], name=op.f('fk_departments_departments_parent_department_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_departments_parent_department_id'), 'departments', ['parent_department_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vendor_code', sa.String(length=32), nullable=False),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('pan_number', sa.String(length=32), nullable=True),
    sa.Column('gst_number', sa.String(length=32), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(name) > 0', name=op.f('ck_vendors_ck_vendors_name')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_created_at'), 'vendors', ['created_at'], unique=False)
    op.create_index(op.f('ix_vendors_gst_number'), 'vendors', ['gst_number'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_pan_number'), 'vendors', ['pan_number'], unique=False)
    op.create_index(op.f('ix_vendors_registration_number'), 'vendors', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=True)
    op.create_table('project_categories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(name) > 0', name=op.f('ck_project_categories_ck_project_categories_name')),
    sa.CheckConstraint('char_length(slug) > 0', name=op.f('ck_project_categories_ck_project_categories_slug')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_project_categories_departments_department_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_categories')),
    sa.UniqueConstraint('department_id', 'slug', name='uq_project_categories_dep_slug')
    )
    op.create_index(op.f('ix_project_categories_created_at'), 'project_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_categories_department_id'), 'project_categories', ['department_id'], unique=False)
    op.create_index(op.f('ix_project_categories_name'), 'project_categories', ['name'], unique=False)
    op.create_index(op.f('ix_project_categories_slug'), 'project_categories', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('citizen','department_official','inspector','contractor','admin')", name=op.f('ck_users_ck_users_role')),
    sa.CheckConstraint("status IN ('active','suspended','deactivated')", name=op.f('ck_users_ck_users_status')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_departments_department_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('reference_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('y_coordinate', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='planned', nullable=False),
    sa.Column('total_budget_sanctioned', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_budget_released', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('department_reported_progress', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('verified_progress', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned','in_progress','completed','halted','delayed')", name=op.f('ck_projects_ck_projects_status')),
    sa.CheckConstraint('char_length(reference_number) > 0', name=op.f('ck_projects_ck_projects_reference_not_empty')),
    sa.CheckConstraint('total_budget_sanctioned >= 0', name=op.f('ck_projects_ck_projects_sanctioned_nonnegative')),
    sa.ForeignKeyConstraint(['category_id'], ['project_categories.id'], name=op.f('fk_projects_project_categories_category_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_projects_departments_department_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_category_id'), 'projects', ['category_id'], unique=False)
    op.create_index(op.f('ix_projects_city'), 'projects', ['city'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_department_id'), 'projects', ['department_id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_reference_number'), 'projects', ['reference_number'], unique=True)
    op.create_index(op.f('ix_projects_state'), 'projects', ['state'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('source_reference', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('create','update','delete','verify','approve','reject','escalate','reverse','withdraw','decision','citizen_submit')", name=op.f('ck_audit_logs_ck_audit_logs_action')),
    sa.CheckConstraint('char_length(entity_type) > 0', name=op.f('ck_audit_logs_ck_audit_logs_entity_type')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_users_actor_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_logs_projects_project_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('financial_year', sa.String(length=16), nullable=False),
    sa.Column('sanctioned_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('released_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_amount <= sanctioned_amount', name=op.f('ck_budgets_ck_budgets_allocated_le_sanctioned')),
    sa.CheckConstraint('allocated_amount >= 0 AND sanctioned_amount >= 0', name=op.f('ck_budgets_ck_budgets_amounts_nonnegative')),
    sa.CheckConstraint('released_amount >= 0 AND spent_amount >= 0', name=op.f('ck_budgets_ck_budgets_movements_nonnegative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_budgets_projects_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets'))
    )
    op.create_index(op.f('ix_budgets_created_at'), 'budgets', ['created_at'], unique=False)
    op.create_index(op.f('ix_budgets_financial_year'), 'budgets', ['financial_year'], unique=False)
    op.create_index(op.f('ix_budgets_project_id'), 'budgets', ['project_id'], unique=True)
    op.create_table('project_locations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(location_name) > 0 OR location_name IS NULL', name=op.f('ck_project_locations_ck_project_locations_name')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_project_locations_ck_project_locations_latitude')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_project_locations_ck_project_locations_longitude')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_locations_projects_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_locations'))
    )
    op.create_index(op.f('ix_project_locations_created_at'), 'project_locations', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_locations_geom'), 'project_locations', ['geom'], unique=False)
    op.create_index(op.f('ix_project_locations_latitude'), 'project_locations', ['latitude'], unique=False)
    op.create_index(op.f('ix_project_locations_location_name'), 'project_locations', ['location_name'], unique=False)
    op.create_index(op.f('ix_project_locations_longitude'), 'project_locations', ['longitude'], unique=False)
    op.create_index(op.f('ix_project_locations_project_id'), 'project_locations', ['project_id'], unique=False)
    op.create_table('project_relationships',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('related_project_id', sa.BigInteger(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.String(length=2000), nullable=True),
    sa.Column('evidence_refs', sa.String(length=4000), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inverse_relationship_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('independent','corridor_shared','overlapping_footprint','same_vendor','sequential_dependency','duplicate_scope','nested_package','superseded_by')", name=op.f('ck_project_relationships_ck_project_relationships_type')),
    sa.CheckConstraint("status IN ('proposed','verified','rejected','expired')", name=op.f('ck_project_relationships_ck_project_relationships_status')),
    sa.CheckConstraint('project_id <> related_project_id', name=op.f('ck_project_relationships_ck_project_relationships_directed')),
    sa.ForeignKeyConstraint(['inverse_relationship_id'], ['project_relationships.id'], name=op.f('fk_project_relationships_project_relationships_inverse_relationship_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_relationships_projects_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], name=op.f('fk_project_relationships_projects_related_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_relationships')),
    sa.UniqueConstraint('project_id', 'related_project_id', 'relationship_type', name='uq_project_relationships_directed')
    )
    op.create_index(op.f('ix_project_relationships_created_at'), 'project_relationships', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_relationships_project_id'), 'project_relationships', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_relationships_related_project_id'), 'project_relationships', ['related_project_id'], unique=False)
    op.create_index(op.f('ix_project_relationships_relationship_type'), 'project_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_project_relationships_status'), 'project_relationships', ['status'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tender_reference', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','under_evaluation','awarded','cancelled','expired')", name=op.f('ck_tenders_ck_tenders_status')),
    sa.CheckConstraint('estimated_value IS NULL OR estimated_value > 0', name=op.f('ck_tenders_ck_tenders_estimated_value')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_tenders_departments_department_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tenders_projects_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenders'))
    )
    op.create_index(op.f('ix_tenders_created_at'), 'tenders', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenders_project_id'), 'tenders', ['project_id'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_tender_reference'), 'tenders', ['tender_reference'], unique=True)
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('contract_reference', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('award_tender_id', sa.BigInteger(), nullable=True),
    sa.Column('contractor_id', sa.BigInteger(), nullable=False),
    sa.Column('awarding_department_id', sa.BigInteger(), nullable=False),
    sa.Column('authorizing_official_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=320), nullable=True),
    sa.Column('scope_of_work', sa.String(length=4000), nullable=True),
    sa.Column('award_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('award_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('escalation_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('variation_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revised_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','completed','terminated','on_hold','disputed')", name=op.f('ck_contracts_ck_contracts_status')),
    sa.CheckConstraint('award_amount > 0', name=op.f('ck_contracts_ck_contracts_award_amount')),
    sa.ForeignKeyConstraint(['authorizing_official_id'], ['users.id'], name=op.f('fk_contracts_users_authorizing_official_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['award_tender_id'], ['tenders.id'], name=op.f('fk_contracts_tenders_award_tender_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['awarding_department_id'], ['departments.id'], name=op.f('fk_contracts_departments_awarding_department_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contractor_id'], ['vendors.id'], name=op.f('fk_contracts_vendors_contractor_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_contracts_projects_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_index(op.f('ix_contracts_authorizing_official_id'), 'contracts', ['authorizing_official_id'], unique=False)
    op.create_index(op.f('ix_contracts_award_tender_id'), 'contracts', ['award_tender_id'], unique=False)
    op.create_index(op.f('ix_contracts_awarding_department_id'), 'contracts', ['awarding_department_id'], unique=False)
    op.create_index(op.f('ix_contracts_contract_reference'), 'contracts', ['contract_reference'], unique=True)
    op.create_index(op.f('ix_contracts_contractor_id'), 'contracts', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contracts_created_at'), 'contracts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('claim_reference', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('claimant_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_id', sa.BigInteger(), nullable=True),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('claimed_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('claimed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','lodged','under_review','supported','partially_supported','rejected')", name=op.f('ck_claims_ck_claims_status')),
    sa.CheckConstraint('claimed_amount IS NULL OR claimed_amount > 0', name=op.f('ck_claims_ck_claims_claimed_positive')),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], name=op.f('fk_claims_users_claimant_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_claims_contracts_contract_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_claims_projects_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_claims_vendors_vendor_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index(op.f('ix_claims_claim_reference'), 'claims', ['claim_reference'], unique=True)
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_claimant_id'), 'claims', ['claimant_id'], unique=False)
    op.create_index(op.f('ix_claims_claimed_date'), 'claims', ['claimed_date'], unique=False)
    op.create_index(op.f('ix_claims_contract_id'), 'claims', ['contract_id'], unique=False)
    op.create_index(op.f('ix_claims_created_at'), 'claims', ['created_at'], unique=False)
    op.create_index(op.f('ix_claims_project_id'), 'claims', ['project_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_index(op.f('ix_claims_vendor_id'), 'claims', ['vendor_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('uploader_id', sa.BigInteger(), nullable=True),
    sa.Column('tender_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('report','financial','bidding','agreement','design','proof','notice','other')", name=op.f('ck_documents_ck_documents_type')),
    sa.CheckConstraint('char_length(title) > 0', name=op.f('ck_documents_ck_documents_title')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_documents_contracts_contract_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_projects_project_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('fk_documents_tenders_tender_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_documents_users_uploader_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_documents_contract_id'), 'documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_documents_tender_id'), 'documents', ['tender_id'], unique=False)
    op.create_index(op.f('ix_documents_uploader_id'), 'documents', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_documents_visibility'), 'documents', ['visibility'], unique=False)
    op.create_table('progress_reports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('report_reference', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('reporter_id', sa.BigInteger(), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_period', sa.String(length=24), nullable=False),
    sa.Column('financial_progress', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('physical_progress', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('verified_progress', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('narrative', sa.String(length=6000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_period IN ('monthly','quarterly','half_yearly','yearly')", name=op.f('ck_progress_reports_ck_progress_reports_period')),
    sa.CheckConstraint('financial_progress IS NULL OR financial_progress BETWEEN 0 AND 100', name=op.f('ck_progress_reports_ck_progress_reports_financial')),
    sa.CheckConstraint('physical_progress IS NULL OR physical_progress BETWEEN 0 AND 100', name=op.f('ck_progress_reports_ck_progress_reports_physical')),
    sa.CheckConstraint('verified_progress IS NULL OR verified_progress BETWEEN 0 AND 100', name=op.f('ck_progress_reports_ck_progress_reports_verified')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_progress_reports_contracts_contract_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_progress_reports_projects_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_progress_reports_users_reporter_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_reports'))
    )
    op.create_index(op.f('ix_progress_reports_contract_id'), 'progress_reports', ['contract_id'], unique=False)
    op.create_index(op.f('ix_progress_reports_created_at'), 'progress_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_progress_reports_project_id'), 'progress_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_progress_reports_report_date'), 'progress_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_progress_reports_report_period'), 'progress_reports', ['report_period'], unique=False)
    op.create_index(op.f('ix_progress_reports_report_reference'), 'progress_reports', ['report_reference'], unique=True)
    op.create_index(op.f('ix_progress_reports_reporter_id'), 'progress_reports', ['reporter_id'], unique=False)
    op.create_table('citizen_reports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('report_reference', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('reported_by_id', sa.BigInteger(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('report_type', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('location_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('photo_document_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('claim_source_id', sa.BigInteger(), nullable=True),
    sa.Column('is_location_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_type IN ('photo','document','complaint','observation','verify_request')", name=op.f('ck_citizen_reports_ck_citizen_reports_type')),
    sa.CheckConstraint("status IN ('submitted','under_review','verified','disputed','rejected','merged')", name=op.f('ck_citizen_reports_ck_citizen_reports_status')),
    sa.CheckConstraint('char_length(description) > 0', name=op.f('ck_citizen_reports_ck_citizen_reports_description')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_citizen_reports_ck_citizen_reports_latitude')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_citizen_reports_ck_citizen_reports_longitude')),
    sa.ForeignKeyConstraint(['claim_source_id'], ['claims.id'], name=op.f('fk_citizen_reports_claims_claim_source_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_citizen_reports_departments_department_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['project_locations.id'], name=op.f('fk_citizen_reports_project_locations_location_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_citizen_reports_projects_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], name=op.f('fk_citizen_reports_users_reported_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizen_reports'))
    )
    op.create_index(op.f('ix_citizen_reports_claim_source_id'), 'citizen_reports', ['claim_source_id'], unique=False)
    op.create_index(op.f('ix_citizen_reports_created_at'), 'citizen_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_citizen_reports_department_id'), 'citizen_reports', ['department_id'], unique=False)
    op.create_index(op.f('ix_citizen_reports_latitude'), 'citizen_reports', ['latitude'], unique=False)
    op.create_index(op.f('ix_citizen_reports_location_geom'), 'citizen_reports', ['location_geom'], unique=False)
    op.create_index(op.f('ix_citizen_reports_location_id'), 'citizen_reports', ['location_id'], unique=False)
    op.create_index(op.f('ix_citizen_reports_longitude'), 'citizen_reports', ['longitude'], unique=False)
    op.create_index(op.f('ix_citizen_reports_project_id'), 'citizen_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_citizen_reports_report_reference'), 'citizen_reports', ['report_reference'], unique=True)
    op.create_index(op.f('ix_citizen_reports_report_type'), 'citizen_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_citizen_reports_reported_at'), 'citizen_reports', ['reported_at'], unique=False)
    op.create_index(op.f('ix_citizen_reports_reported_by_id'), 'citizen_reports', ['reported_by_id'], unique=False)
    op.create_index(op.f('ix_citizen_reports_status'), 'citizen_reports', ['status'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('decision_reference', sa.String(length=64), nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('adjudicator_id', sa.BigInteger(), nullable=True),
    sa.Column('decision_state', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=4000), nullable=True),
    sa.Column('supporting_evidence', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('conflicting_evidence', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('missing_information', sa.ARRAY(sa.String(length=400)), nullable=True),
    sa.Column('sources', sa.ARRAY(sa.String(length=200)), nullable=True),
    sa.Column('dates', sa.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision_state IN ('PROVEN_SUPPORTED','PROVEN_REJECTED','INCOMPLETE','CONFLICTING','QUESTIONABLE','HUMAN_REVIEW_REQUIRED','INSUFFICIENT')", name=op.f('ck_decisions_ck_decisions_state')),
    sa.CheckConstraint('event_date IS NULL OR decision_date IS NULL OR event_date <= decision_date', name=op.f('ck_decisions_ck_decisions_event_before_decision')),
    sa.CheckConstraint('source IS NULL OR char_length(source) = 64', name=op.f('ck_decisions_ck_decisions_source_len')),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['users.id'], name=op.f('fk_decisions_users_adjudicator_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_decisions_claims_claim_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_decisions_projects_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_adjudicator_id'), 'decisions', ['adjudicator_id'], unique=False)
    op.create_index(op.f('ix_decisions_claim_id'), 'decisions', ['claim_id'], unique=False)
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_decisions_decision_date'), 'decisions', ['decision_date'], unique=False)
    op.create_index(op.f('ix_decisions_decision_reference'), 'decisions', ['decision_reference'], unique=True)
    op.create_index(op.f('ix_decisions_decision_state'), 'decisions', ['decision_state'], unique=False)
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_id', sa.BigInteger(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('claim_id', sa.BigInteger(), nullable=True),
    sa.Column('capture_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('chain_trace', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('citizen_photo','citizen_report','document','inspection','claim','decision')", name=op.f('ck_evidence_ck_evidence_source_type')),
    sa.CheckConstraint("status IN ('pending','verified','disputed','rejected','superseded')", name=op.f('ck_evidence_ck_evidence_status')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_claims_claim_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_evidence_documents_document_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_evidence_projects_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_evidence_users_uploaded_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_capture_geom'), 'evidence', ['capture_geom'], unique=False)
    op.create_index(op.f('ix_evidence_captured_at'), 'evidence', ['captured_at'], unique=False)
    op.create_index(op.f('ix_evidence_checksum_sha256'), 'evidence', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidence_status'), 'evidence', ['status'], unique=False)
    op.create_index(op.f('ix_evidence_uploaded_by_id'), 'evidence', ['uploaded_by_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('inspection_reference', sa.String(length=48), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('inspector_id', sa.BigInteger(), nullable=True),
    sa.Column('contractor_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('findings', sa.String(length=6000), nullable=True),
    sa.Column('inspection_type', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('report_document_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("inspection_type IN ('pre_construction','materials_sampling','site_inspection','completion_review','defect_liability_review','special_audit')", name=op.f('ck_inspections_ck_inspections_type')),
    sa.CheckConstraint("outcome IN ('passed','passed_with_recommendations','failed','aborted')", name=op.f('ck_inspections_ck_inspections_outcome')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_inspections_ck_inspections_latitude')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_inspections_ck_inspections_longitude')),
    sa.ForeignKeyConstraint(['contractor_id'], ['vendors.id'], name=op.f('fk_inspections_vendors_contractor_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], name=op.f('fk_inspections_users_inspector_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_inspections_projects_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_document_id'], ['documents.id'], name=op.f('fk_inspections_documents_report_document_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    op.create_index(op.f('ix_inspections_conducted_at'), 'inspections', ['conducted_at'], unique=False)
    op.create_index(op.f('ix_inspections_contractor_id'), 'inspections', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_inspections_created_at'), 'inspections', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspections_geom'), 'inspections', ['geom'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_reference'), 'inspections', ['inspection_reference'], unique=True)
    op.create_index(op.f('ix_inspections_inspection_type'), 'inspections', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspections_latitude'), 'inspections', ['latitude'], unique=False)
    op.create_index(op.f('ix_inspections_longitude'), 'inspections', ['longitude'], unique=False)
    op.create_index(op.f('ix_inspections_project_id'), 'inspections', ['project_id'], unique=False)
    op.create_index(op.f('ix_inspections_report_document_id'), 'inspections', ['report_document_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('payment_reference', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger(), nullable=True),
    sa.Column('supporting_document_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_type IN ('advance','milestone','final','retention','supplementary')", name=op.f('ck_payments_ck_payments_type')),
    sa.CheckConstraint("status IN ('recorded','pending','approved','rejected','reversed')", name=op.f('ck_payments_ck_payments_status')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_payments_contracts_contract_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_payments_projects_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_payments_users_recorded_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supporting_document_id'], ['documents.id'], name=op.f('fk_payments_documents_supporting_document_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_payments_vendors_vendor_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_contract_id'), 'payments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_payments_project_id'), 'payments', ['project_id'], unique=False)
    op.create_index(op.f('ix_payments_recorded_by_id'), 'payments', ['recorded_by_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_supporting_document_id'), 'payments', ['supporting_document_id'], unique=False)
    op.create_index(op.f('ix_payments_vendor_id'), 'payments', ['vendor_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('anomaly_reference', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('evidence_id', sa.BigInteger(), nullable=True),
    sa.Column('detected_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('resolution_note', sa.String(length=2000), nullable=True),
    sa.Column('resolution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("anomaly_type IN ('cost_overrun','schedule_delay','progress_discrepancy','payment_anomaly','documentation_gap','evidence_conflict','vendor_violation','other')", name=op.f('ck_anomalies_ck_anomalies_type')),
    sa.CheckConstraint("severity IN ('info','notice','warning','critical')", name=op.f('ck_anomalies_ck_anomalies_severity')),
    sa.CheckConstraint("status IN ('open','investigating','confirmed','resolved','dismissed','escalated')", name=op.f('ck_anomalies_ck_anomalies_status')),
    sa.CheckConstraint('confidence IS NULL OR confidence BETWEEN 0 AND 1', name=op.f('ck_anomalies_ck_anomalies_confidence')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_anomalies_contracts_contract_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detected_by_user_id'], ['users.id'], name=op.f('fk_anomalies_users_detected_by_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_anomalies_evidence_evidence_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_anomalies_projects_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    op.create_index(op.f('ix_anomalies_anomaly_reference'), 'anomalies', ['anomaly_reference'], unique=True)
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_contract_id'), 'anomalies', ['contract_id'], unique=False)
    op.create_index(op.f('ix_anomalies_created_at'), 'anomalies', ['created_at'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_by_user_id'), 'anomalies', ['detected_by_user_id'], unique=False)
    op.create_index(op.f('ix_anomalies_evidence_id'), 'anomalies', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_anomalies_project_id'), 'anomalies', ['project_id'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_status'), 'anomalies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_status'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_project_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_evidence_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_by_user_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_created_at'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_contract_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_reference'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_payments_vendor_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_supporting_document_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_recorded_by_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_project_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_contract_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_inspections_report_document_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_project_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_longitude'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_latitude'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_type'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_reference'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_geom'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_created_at'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_contractor_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_conducted_at'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_evidence_uploaded_by_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_checksum_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_captured_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_capture_geom'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_state'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_reference'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_date'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_claim_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_adjudicator_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_citizen_reports_status'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_reported_by_id'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_reported_at'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_report_type'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_report_reference'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_project_id'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_longitude'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_location_id'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_location_geom'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_latitude'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_department_id'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_created_at'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_claim_source_id'), table_name='citizen_reports')
    op.drop_table('citizen_reports')
    op.drop_index(op.f('ix_progress_reports_reporter_id'), table_name='progress_reports')
    op.drop_index(op.f('ix_progress_reports_report_reference'), table_name='progress_reports')
    op.drop_index(op.f('ix_progress_reports_report_period'), table_name='progress_reports')
    op.drop_index(op.f('ix_progress_reports_report_date'), table_name='progress_reports')
    op.drop_index(op.f('ix_progress_reports_project_id'), table_name='progress_reports')
    op.drop_index(op.f('ix_progress_reports_created_at'), table_name='progress_reports')
    op.drop_index(op.f('ix_progress_reports_contract_id'), table_name='progress_reports')
    op.drop_table('progress_reports')
    op.drop_index(op.f('ix_documents_visibility'), table_name='documents')
    op.drop_index(op.f('ix_documents_uploader_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tender_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_contract_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_claims_vendor_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_project_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_created_at'), table_name='claims')
    op.drop_index(op.f('ix_claims_contract_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claimed_date'), table_name='claims')
    op.drop_index(op.f('ix_claims_claimant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_reference'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_created_at'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contractor_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_reference'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_awarding_department_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_award_tender_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_authorizing_official_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_tenders_tender_reference'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_project_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_created_at'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_project_relationships_status'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_relationship_type'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_related_project_id'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_project_id'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_created_at'), table_name='project_relationships')
    op.drop_table('project_relationships')
    op.drop_index(op.f('ix_project_locations_project_id'), table_name='project_locations')
    op.drop_index(op.f('ix_project_locations_longitude'), table_name='project_locations')
    op.drop_index(op.f('ix_project_locations_location_name'), table_name='project_locations')
    op.drop_index(op.f('ix_project_locations_latitude'), table_name='project_locations')
    op.drop_index(op.f('ix_project_locations_geom'), table_name='project_locations')
    op.drop_index(op.f('ix_project_locations_created_at'), table_name='project_locations')
    op.drop_table('project_locations')
    op.drop_index(op.f('ix_budgets_project_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_financial_year'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_created_at'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_state'), table_name='projects')
    op.drop_index(op.f('ix_projects_reference_number'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_department_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_city'), table_name='projects')
    op.drop_index(op.f('ix_projects_category_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_project_categories_slug'), table_name='project_categories')
    op.drop_index(op.f('ix_project_categories_name'), table_name='project_categories')
    op.drop_index(op.f('ix_project_categories_department_id'), table_name='project_categories')
    op.drop_index(op.f('ix_project_categories_created_at'), table_name='project_categories')
    op.drop_table('project_categories')
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_registration_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_pan_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_gst_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_created_at'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_departments_parent_department_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
